include: mathvision_testmini.yaml
task: "mathvision_testmini_prompt_in_image"
dataset_path: YongxinWang/math-prompt-in-image
dataset_name: mathvision_testmini_prompt_in_image
dataset_kwargs: {}
test_split: testmini
doc_to_visual: !function utils.mathvision_doc_to_visual
doc_to_text: !function utils.mathvision_doc_to_text_minimal
